### ISSUE TITLE
Ограничение в 10 запросов в минуту

### ISSUE THREAD

**Issue by kiriharu** [catspace-dev/hostinfobot#9]

**Comment by sfsef** [comment]
10 запросов в минуту не мало?

**Comment by sfsef** [comment]
Я понимаю если там нагрузка будет большая на бота, но сейчас не вижу пока смысла

**Comment by kiriharu** [comment]
В итоге сделал 2 секунды кулдаун на каждый запрос.

**Comment by sfsef** [comment]
Угу. Отлично
Done
